const errCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_BODY: 'INVALID_BODY',
  INVALID_QUERY_PARAM: 'INVALID_QUERY_PARAM',
  INVALID_HEADER: 'INVALID_HEADER',
}

export default errCodes
